version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: email_validator
    versions:
    - ">= 2.a, < 3"
  - dependency-name: govuk_frontend_toolkit
    versions:
    - ">= 9.a, < 10"
  - dependency-name: moj_template
    versions:
    - "> 0.23.0, < 1"
  - dependency-name: shoulda-matchers
    versions:
    - ">= 4.a, < 5"
  - dependency-name: sidekiq
    versions:
    - 5.2.4
  - dependency-name: sprockets
    versions:
    - ">= 4.0.a, < 4.1"
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.9.0
    - 1.9.1
  - dependency-name: parallel_tests
    versions:
    - 3.4.0
    - 3.5.0
    - 3.5.1
    - 3.5.2
    - 3.6.0
  - dependency-name: webmock
    versions:
    - 3.11.3
    - 3.12.0
    - 3.12.1
  - dependency-name: fog-aws
    versions:
    - 3.9.0
  - dependency-name: rails
    versions:
    - 6.1.3
  - dependency-name: carrierwave
    versions:
    - 2.1.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
  - dependency-name: sidekiq
    versions:
    - 6.1.3
  - dependency-name: redcarpet
    versions:
    - 3.5.1
  - dependency-name: iodine
    versions:
    - 0.7.43
  - dependency-name: webrick
    versions:
    - 1.6.1
  - dependency-name: dotenv-rails
    versions:
    - 2.7.6
  - dependency-name: bcrypt
    versions:
    - 3.1.16
  - dependency-name: factory_bot_rails
    versions:
    - 6.1.0
  - dependency-name: rubocop-rspec
    versions:
    - 1.41.0
