AllCops:
  TargetRubyVersion: 3.3.5
  SuggestExtensions: false
  Exclude:
    - 'Guardfile'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - 'spec/rails_helper.rb'
    - 'lib/tasks/cucumber.rake'
    - 'features/support/env.rb'
    - 'script/cucumber'
    - 'lib/log_stuff.rb'
    - 'config/routes.rb'
    - 'Gemfile'
    - 'spec/support/**/*'
    - 'node_modules/**/*'

# Metrics
Metrics/ClassLength:
  Exclude:
    - 'app/forms/**/*'
    - 'features/support/page_objects/**/*'
    - 'features/support/sections/**/*'
Metrics/ModuleLength:
  Exclude:
    - 'spec/forms/**/*'
    - 'features/support/page_objects/**/*'
    - 'features/support/sections/**/*'
Metrics/AbcSize:
  Exclude:
    - 'spec/**/*'
  Max: 20
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'
    - 'app/models/ability.rb'
    - 'config/initializers/markdown_handler.rb'
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*.rb'
    - '**/*.jbuilder'
  Max: 25
Metrics/CollectionLiteralLength:
  Enabled: true

# Style
Style/BlockDelimiters:
  Enabled: true
  Exclude:
    - 'spec/**/*'
Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Layout/EmptyLineAfterMagicComment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: annotated
Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'spec/features/attaching_a_document_spec.rb'
Style/MutableConstant:
  Enabled: true
Style/NumericPredicate:
  Exclude:
    - 'spec/**/*'
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%w': '[]'
    '%W': '[]'
    '%i': '[]'
Style/RegexpLiteral:
  Enabled: false
Style/StringConcatenation:
  Enabled: true
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  EnforcedStyle: brackets
Style/TrailingCommaInHashLiteral:
  Enabled: true
Style/TrivialAccessors:
  AllowPredicates: true
Style/WordArray:
  EnforcedStyle: brackets
Style/SuperArguments:
  Enabled: false
Style/SuperWithArgsParentheses:
  Enabled: true
Style/SwapValues:
  Enabled: true
Style/YAMLFileRead:
  Enabled: true
Style/RedundantRegexpConstructor:
  Enabled: true
Style/RedundantSelfAssignmentBranch:
  Enabled: true
Style/RedundantStringEscape:
  Enabled: true
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
Style/SafeNavigationChainLength:
  Enabled: true
Style/SelectByRegexp:
  Enabled: true
Style/SendWithLiteralMethodName:
  Enabled: true
Style/SingleLineDoEndBlock:
  Enabled: true
Style/StringChars:
  Enabled: true
Style/RedundantCurrentDirectoryInPath:
  Enabled: true
Style/RedundantDoubleSplatHashBraces:
  Enabled: true
Style/RedundantEach:
  Enabled: true
Style/RedundantFilterChain:
  Enabled: true
Style/RedundantHeredocDelimiterQuotes:
  Enabled: true
Style/RedundantInitialize:
  Enabled: true
Style/RedundantInterpolationUnfreeze:
  Enabled: true
Style/RedundantLineContinuation:
  Enabled: true
Style/RedundantRegexpArgument:
  Enabled: true
Style/NumberedParameters:
  Enabled: true
Style/NumberedParametersLimit:
  Enabled: true
Style/ObjectThen:
  Enabled: true
Style/OpenStructUse:
  Enabled: true
Style/OperatorMethodCall:
  Enabled: true
Style/QuotedSymbols:
  Enabled: true
Style/RedundantArgument:
  Enabled: true
Style/RedundantArrayConstructor:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/MapCompactWithConditionalBlock:
  Enabled: true
Style/MapIntoArray:
  Enabled: true
Style/MapToHash:
  Enabled: true
Style/MapToSet:
  Enabled: true
Style/MinMaxComparison:
  Enabled: true
Style/MultilineInPatternThen:
  Enabled: true
Style/NegatedIfElseCondition:
  Enabled: true
Style/NestedFileDirname:
  Enabled: true
Style/NilLambda:
  Enabled: true
Style/FileRead:
  Enabled: true
Style/FileTouch:
  Enabled: true
Style/FileWrite:
  Enabled: true
Style/HashConversion:
  Enabled: true
Style/HashExcept:
  Enabled: true
Style/IfWithBooleanLiteralBranches:
  Enabled: true
Style/InPatternThen:
  Enabled: true
Style/KeywordArgumentsMerging:
  Enabled: true
Style/MagicCommentFormat:
  Enabled: true
Style/DirEmpty:
  Enabled: true
Style/DocumentDynamicEvalDefinition:
  Enabled: true
Style/EmptyHeredoc:
  Enabled: true
Style/EndlessMethod:
  Enabled: true
Style/EnvHome:
  Enabled: true
Style/ExactRegexpMatch:
  Enabled: true
Style/FetchEnvVar:
  Enabled: true
Style/FileEmpty:
  Enabled: true
Style/FileNull:
  Enabled: true
Style/ArgumentsForwarding:
  Enabled: false
Style/ArrayIntersect:
  Enabled: true
Style/BitwisePredicate:
  Enabled: true
Style/CollectionCompact:
  Enabled: true
Style/CombinableDefined:
  Enabled: true
Style/ComparableClamp:
  Enabled: true
Style/ConcatArrayLiterals:
  Enabled: true
Style/DataInheritance:
  Enabled: true
Style/DigChain:
  Enabled: true
Style/AmbiguousEndlessMethodDefinition:
  Enabled: true

# Lint
Lint/AssignmentInCondition:
  AllowSafeAssignment: false
Lint/ConstantDefinitionInBlock:
  Enabled: true
Lint/EmptyFile:
  Exclude:
    - 'config/nulldb_schema.rb'
Lint/IneffectiveAccessModifier:
  Enabled: true
Lint/MissingCopEnableDirective:
  Enabled: true
Lint/UnusedMethodArgument:
  Enabled: true
Lint/UselessAccessModifier:
  Enabled: true
Lint/UselessDefined:
  Enabled: true
Lint/UselessNumericOperation:
  Enabled: true
Lint/UselessRescue:
  Enabled: true
Lint/UselessRuby2Keywords:
  Enabled: true
Lint/RefinementImportMethods:
  Enabled: true
Lint/RequireRangeParentheses:
  Enabled: true
Lint/RequireRelativeSelfPath:
  Enabled: true
Lint/SymbolConversion:
  Enabled: true
Lint/ToEnumArguments:
  Enabled: true
Lint/TripleQuotes:
  Enabled: true
Lint/UnescapedBracketInRegexp:
  Enabled: true
Lint/UnexpectedBlockArity:
  Enabled: true
Lint/UnmodifiedReduceAccumulator:
  Enabled: true
Lint/LiteralAssignmentInCondition:
  Enabled: true
Lint/MixedCaseRange:
  Enabled: true
Lint/NoReturnInBeginEndBlocks:
  Enabled: true
Lint/NonAtomicFileOperation:
  Enabled: true
Lint/NumberedParameterAssignment:
  Enabled: true
Lint/NumericOperationWithConstantResult:
  Enabled: true
Lint/OrAssignmentToConstant:
  Enabled: true
Lint/RedundantDirGlobSort:
  Enabled: true
Lint/RedundantRegexpQuantifiers:
  Enabled: true
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: true
Lint/DuplicateSetElement:
  Enabled: true
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: true
Lint/EmptyInPattern:
  Enabled: true
Lint/HashNewWithKeywordArgumentsAsDefault:
  Enabled: true
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: true
Lint/ItWithoutArgumentsInBlock:
  Enabled: true
Lint/LambdaWithoutLiteralBlock:
  Enabled: true
Lint/AmbiguousAssignment:
  Enabled: true
Lint/AmbiguousOperatorPrecedence:
  Enabled: true
Lint/AmbiguousRange:
  Enabled: true
Lint/ConstantOverwrittenInRescue:
  Enabled: true
Lint/DeprecatedConstants:
  Enabled: true
Lint/DuplicateBranch:
  Enabled: false
Lint/DuplicateMagicComment:
  Enabled: true
Lint/DuplicateMatchPattern:
  Enabled: true

# Documentation
Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# RSpec
RSpec/DescribeClass:
  Exclude:
    - spec/support/**/*
    - spec/views/**/*
RSpec/EmptyLineAfterExampleGroup:
  Enabled: true
RSpec/EmptyLineAfterFinalLet:
  Enabled: true
RSpec/ExampleLength:
  Exclude:
    - 'spec/**/*'
RSpec/ExampleWording:
  Enabled: true
RSpec/ExpectActual:
  Exclude:
    - 'spec/routing/**/*'
RSpec/ExpectInHook:
  Enabled: true
Rails/FilePath:
  Exclude:
    - 'spec/services/carrierwave_filename_spec.rb'
RSpec/LeakyConstantDeclaration:
  Enabled: true
RSpec/LetBeforeExamples:
  Enabled: true
RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'
RSpec/NamedSubject:
  Enabled: true
RSpec/NotToNot:
  Enabled: true
RSpec/RepeatedDescription:
  Enabled: true
RSpec/ScatteredSetup:
  Enabled: true
  Exclude:
    - "spec/features/create_claim_applications_spec.rb"
RSpec/StubbedMock:
  Enabled: true
RSpec/NestedGroups:
  Max: 10
RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/forms/refunds/**/*_spec.rb'
RSpec/MessageSpies:
  EnforcedStyle: receive
RSpec/MultipleMemoizedHelpers:
  Exclude:
    - 'spec/views/claim_reviews/show/review_page_employment_spec.rb'
    - 'spec/models/stats/claim_stats_spec.rb'
    - 'spec/forms/refunds/review_form_spec.rb'
    - 'spec/forms/refunds/confirmation_form_spec.rb'
    - 'spec/forms/additional_claimants_upload_form_spec.rb'
    - 'spec/features/terms_spec.rb'
    - 'spec/features/guide_spec.rb'
    - 'spec/features/create_claim_applications_spec.rb'
    - 'spec/features/attaching_a_document_spec.rb'
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/VerifiedDoubleReference:
  Enabled: false
RSpec/StringAsInstanceDoubleConstant:
  Enabled: false
RSpec/NoExpectationExample:
  Enabled: false
RSpec/PendingWithoutReason:
  Enabled: false

# RSpec Rails
RSpecRails/AvoidSetupHook:
  Enabled: true
RSpecRails/HaveHttpStatus:
  Enabled: true
RSpecRails/InferredSpecType:
  Enabled: false
RSpecRails/MinitestAssertions:
  Enabled: true
RSpecRails/NegationBeValid:
  Enabled: true
RSpecRails/TravelAround:
  Enabled: false

# Capybara
Capybara/CurrentPathExpectation:
  Enabled: true
Capybara/ClickLinkOrButtonStyle:
  Enabled: true
Capybara/MatchStyle:
  Enabled: true
Capybara/NegationMatcher:
  Enabled: true
Capybara/RedundantWithinFind:
  Enabled: true
Capybara/SpecificActions:
  Enabled: true
Capybara/SpecificFinders:
  Enabled: true
Capybara/SpecificMatcher:
  Enabled: true
Capybara/RSpec/HaveSelector:
  Enabled: true

# Rails
Rails/Blank:
  Enabled: true
  Exclude:
    - 'app/views/api/claim/_build_primary_representative.json.jbuilder'
    - 'app/controllers/claims_controller.rb'
Rails/Date:
  Enabled: true
Rails/LexicallyScopedActionFilter:
  Enabled: true
  Exclude:
    - 'app/controllers/save_and_return/sessions_controller.rb'
Rails/SkipsModelValidations:
  Enabled: false
Rails/InverseOf:
  Enabled: false
Rails/HasManyOrHasOneDependent:
  Enabled: false
Rails/EnumSyntax:
  Enabled: true
Rails/WhereRange:
  Enabled: false
Rails/TopLevelHashWithIndifferentAccess:
  Enabled: true
Rails/TransactionExitStatement:
  Enabled: true
Rails/UnusedRenderContent:
  Enabled: true
Rails/WhereEquals:
  Enabled: true
Rails/WhereExists:
  Enabled: true
Rails/WhereMissing:
  Enabled: true
Rails/WhereNot:
  Enabled: true
Rails/WhereNotWithMultipleConditions:
  Enabled: true
Rails/RootPublicPath:
  Enabled: true
Rails/SelectMap:
  Enabled: true
Rails/ShortI18n:
  Enabled: true
Rails/SquishedSQLHeredocs:
  Enabled: false
Rails/StripHeredoc:
  Enabled: false
Rails/ThreeStateBooleanColumn:
  Enabled: true
Rails/TimeZoneAssignment:
  Enabled: true
Rails/ToFormattedS:
  Enabled: true
Rails/ToSWithArgument:
  Enabled: true
Rails/PluckInWhere:
  Enabled: true
Rails/RedundantActiveRecordAllMethod:
  Enabled: true
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: true
Rails/RedundantTravelBack:
  Enabled: false
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ResponseParsedBody:
  Enabled: true
Rails/RootJoinChain:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Rails/I18nLocaleAssignment:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
Rails/IgnoredColumnsAssignment:
  Enabled: true
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/MigrationClassName:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
Rails/Pluck:
  Enabled: true
Rails/DuplicateScope:
  Enabled: true
Rails/DurationArithmetic:
  Enabled: true
Rails/EagerEvaluationLogMessage:
  Enabled: true
Rails/EnvLocal:
  Enabled: true
Rails/ExpandedDateRange:
  Enabled: true
Rails/FindById:
  Enabled: false
Rails/FreezeTime:
  Enabled: true
Rails/I18nLazyLookup:
  Enabled: true
Rails/ActiveSupportOnLoad:
  Enabled: true
Rails/AddColumnIndex:
  Enabled: true
Rails/AfterCommitOverride:
  Enabled: true
Rails/AttributeDefaultBlockValue:
  Enabled: true
Rails/CompactBlank:
  Enabled: true
Rails/DangerousColumnNames:
  Enabled: true
Rails/DeprecatedActiveModelErrorsMethods:
  Enabled: true
Rails/DotSeparatedKeys:
  Enabled: true
Rails/DuplicateAssociation:
  Enabled: true
Rails/ActionControllerFlashBeforeRender:
  Enabled: true
Rails/ActionControllerTestCase:
  Enabled: true
Rails/ActionOrder:
  Enabled: true
Rails/ActiveRecordCallbacksOrder:
  Enabled: true

# Layout
Layout/AccessModifierIndentation:
  EnforcedStyle: indent
Layout/BlockAlignment:
  Enabled: true
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLines:
  Enabled: true
Layout/ExtraSpacing:
  Enabled: true
Layout/InitialIndentation:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/LineLength:
  Max: 120
  Exclude:
    - 'features/**/*'
    - 'spec/**/*'
    - 'Gemfile'
    - 'import-secrets.rb'
    - 'config/initializers/devise.rb'
    - 'config/environments/*.rb'
    - 'app/validators/ccd_phone_validator.rb'
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
Layout/TrailingEmptyLines:
  Enabled: true
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/LineContinuationLeadingSpace:
  Enabled: true
Layout/LineContinuationSpacing:
  Enabled: true
Layout/LineEndStringConcatenationIndentation:
  Enabled: true
Layout/SpaceBeforeBrackets:
  Enabled: true

# Naming
Naming/FileName:
  Exclude:
    - "import-secrets.rb"
Naming/PredicateName:
  Enabled: false
Naming/BlockForwarding:
  Enabled: true

# Gemspec
Gemspec/AddRuntimeDependency:
  Enabled: false
Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false

# Factory Bot
FactoryBot/AssociationStyle:
  Enabled: false
FactoryBot/ConsistentParenthesesStyle:
  Enabled: true
FactoryBot/ExcessiveCreateList:
  Enabled: true
FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false
FactoryBot/FactoryNameStyle:
  Enabled: true
FactoryBot/IdSequence:
  Enabled: true
FactoryBot/RedundantFactoryOption:
  Enabled: true
FactoryBot/SyntaxMethods:
  Enabled: true

# Security
Security/CompoundHash:
  Enabled: true
Security/IoMethods:
  Enabled: true

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec_rails
