sudo: false
language: ruby
rvm:
- 2.2.0
node_js:
- '0.10'
addons:
  apt:
    packages:
      - pdftk
  postgresql: '9.3'
before_script:
- npm install
- bin/rake db:create db:migrate
env:
  global:
    secure: FNL+FZauJ7fy1rT4luEvPGuAErxyp4BicM5bXCD/dBHMNI6rhGDulMhnqdThAaR4DvhCXaBahrnNFs7gfilpdkQzz3zYVBqvjlyx4slIL6xRTKOwVo6X6tG804ZiJ2b8sMTCqBBn5xoVCjDcle+VCcQNp2oq/LoXGGPHdx/LcKY=
