version: "2"

services:
  web:
    build:
      context: .
    links: 
      - db
      #- redis
    ports:
      - 8080:8080
      - 3000:3000
    env_file: .env
    environment:
      DB_NAME: atet_development
      DB_USERNAME: atet
      DB_PASSWORD: atet
      DB_HOST: db

  db:
    image: postgres
    environment:
      POSTGRES_DB: atet_development
      POSTGRES_USER: atet
      POSTGRES_PASSWORD: atet

#  sidekiq:
#    build:
#      context: .
#      dockerfile: ./docker/rails/Dockerfile
#    links:
#      - db
#      - redis
#    env_file: .env
#    command: bash -c "bundle exec sidekiq -c 5 -v -e local"

#  redis:
#    image: redis
#    ports:
#      - 6379
