version: '3'
services:
  ruby:
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      SELENIUM_URL: 'http://zalenium:4444/wd/hub'
      TEST_BROWSER: 'chrome'
    image: garytaylor/et_docker_workspace:0.1.4
    volumes:
      - rubygems_cache:/usr/local/bundle
  db:
    image: postgres:9.6
  zalenium:
    image: "dosel/zalenium"
    hostname: zalenium
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 1280 --screenHeight 720
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME
      - SAUCE_ACCESS_KEY
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
volumes:
  rubygems_cache:
