version: "2"

services:
  test:
    image: moj_et_test
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - db
      - selenium
    environment:
      GEM_HOME: '/rubygems'
      BUNDLE_PATH: '/rubygems'
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      RAILS_ENV: 'test'
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
      TEST_BROWSER: 'chrome'
      GOOGLE_ANALYTICS_ID: moj_et_test
      HTTP_OPEN_TIMEOUT_S: 100
      HTTP_READ_TIMEOUT_S: 100
      JADU_API: https://fgr-stub-service.herokuapp.com/1/
      S3_UPLOAD_BUCKET: "${S3_UPLOAD_BUCKET:-etuploads}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY:-anything}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-anything}"
      SERVICE_NOW_EMAIL: fake@servicenow.fake.com
    volumes:
      - rubygems_cache:/rubygems
      - npm_cache:/app/node_modules
    command: /bin/bash -c "bundle && npm install && bundle exec rake db:create db:migrate assets:precompile cucumber"
  db:
    image: postgres:9.6
  selenium:
    image: selenium/standalone-chrome-debug
    volumes:
      - /dev/shm:/dev/shm
volumes:
  rubygems_cache:
  npm_cache:

