version: "2"

services:
  test:
    image: moj_et_test
    build:
      context: .
      dockerfile: Dockerfile.test
    links:
      - db
      - selenium
    environment:
      GEM_HOME: '/rubygems'
      BUNDLE_PATH: '/rubygems'
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      RAILS_ENV: 'test'
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
      DRIVER: 'chrome'
      JADU_API: 'https://fgr-stub-service.herokuapp.com/1/'
      HTTP_OPEN_TIMEOUT_S: 100
      HTTP_READ_TIMEOUT_S: 100
    volumes:
      - rubygems_cache:/rubygems
    command: rake db:create db:migrate assets:precompile default cucumber
  db:
    image: postgres:9.3
  selenium:
    image: selenium/standalone-chrome
volumes:
  rubygems_cache:


