version: "2"

services:
  test:
    build: .
    links:
      - db
      - selenium
    environment:
      GEM_HOME: '/rubygems'
      BUNDLE_PATH: '/rubygems'
      RAILS_ENV: 'test'
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
      CAPYBARA_APP_HOST: 'http://test:3000'
      CAPYBARA_SERVER_HOST: 'test'
    volumes:
      - rubygems_cache:/rubygems
  db:
    image: postgres
  selenium:
    image: selenium/standalone-chrome
volumes:
  rubygems_cache:


