version: "2"

services:
  test:
    build: .
    links:
      - db
      - selenium
    environment:
      RAILS_ENV: 'test'
      SELENIUM_URL: 'http://selenium:4444/wd/hub'
      CAPYBARA_APP_HOST: 'http://test:3000'
      CAPYBARA_SERVER_HOST: 'test'
  db:
    image: postgres
  selenium:
    image: selenium/standalone-chrome

