version: "3"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        source_image: ${SOURCE_DOCKER_IMAGE}
    links:
      - db
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      TEST_BROWSER: 'firefox_local'
      GOOGLE_ANALYTICS_ID: moj_et_test
      HTTP_OPEN_TIMEOUT_S: 100
      HTTP_READ_TIMEOUT_S: 100
      SERVICE_NOW_EMAIL: fake@servicenow.fake.com
      RAILS_LOG_LEVEL: info
      WAIT_HOSTS: db:5432

    volumes:
      - ./tmp/capybara:/home/app/et1/tmp/capybara
  db:
    image: postgres:9.6
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

