base:
  applicationPort: 8080
  readinessPath: /apply/ping.json
  livenessPath: /apply/ping.json
  startupPath: /apply/ping.json
  image: "hmctspublic.azurecr.io/et-pet/et1:latest"
  ingressHost: et-pet-et1.{{ .Values.global.environment }}.platform.hmcts.net
  aadIdentityName: et-pet
  environment:
    RAILS_ENV: production
    RAILS_LOG_TO_STDOUT: true
    ABSOLUTE_HOST: "http://et-dev-azure.dev.et.dsd.io"
    REMOVE_ASSET_HOST: "https://bbea327e42bedevet1.blob.core.windows.net/"
    RAILS_SERVE_STATIC_FILES: true
    CLOUD_PROVIDER: "azure"
    HTTP_OPEN_TIMEOUT_S: 60
    HTTP_READ_TIMEOUT_S: 60
    ET_API_URL: "http://et-api.employmenttribunal:8080/api/v2/"
    SENDING_HOST: "https://et-dev-azure.dev.et.dsd.io"
    WEB_CONCURRENCY: 2
    RAILS_LOG_LEVEL: "info"
    SMTP_HOSTNAME: "smtp.sendgrid.net"
    SMTP_PORT: 587
    DOCKER_STATE: "migrate"
    SERVICE_NOW_EMAIL: "DCD-ETOnlineServiceDesk@HMCTS.NET"
    AZURE_APP_INSIGHTS_ROLE_NAME: "ET1"
  keyVaults:
    et-pet:
      secrets:
        - name: et1-postgres-host
          alias: DB_HOST
        - name: et1-postgres-port
          alias: DB_PORT
        - name: et1-postgres-user
          alias: DB_USERNAME
        - name: et1-postgres-database
          alias: DB_NAME
        - name: et1-google-analytics-id
          alias: GOOGLE_ANALYTICS_ID
        - name: et1-secret-key-base
          alias: SECRET_KEY_BASE
        - name: et1-secret-key-token
          alias: SECRET_KEY_TOKEN
        - name: et1-zendesk-group-id
          alias: ZENDESK_GROUP_ID
        - name: et1-zendesk-token
          alias: ZENDESK_TOKEN
        - name: et1-zendesk-url
          alias: ZENDESK_URL
        - name: et1-zendesk-user
          alias: ZENDESK_USER
        - name: sendgrid-username
          alias: SMTP_USERNAME
        - name: sendgrid-password
          alias: SMTP_PASSWORD
        - name: et1-raven-dsn
          alias: RAVEN_DSN
        - name: govuk-notify-api-key
          alias: GOVUK_NOTIFY_API_KEY_LIVE
        - name: et1-gtm-account
          alias: GTM_ACCOUNT
